name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3.2.0
        with:
          # You can customize these options
          github_user: 'YOUR_GITHUB_USERNAME'
          output: 'snake-game.gif' # or 'snake-game.svg'
          width: 800
          height: 600

      - name: Upload Snake Game
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: snake-game.gif # or 'snake-game.svg'
